// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getArtistByID = `-- name: GetArtistByID :one
SELECT id, created_at, updated_at, name, bio, image_url FROM artists WHERE id = $1
`

func (q *Queries) GetArtistByID(ctx context.Context, id pgtype.UUID) (Artist, error) {
	row := q.db.QueryRow(ctx, getArtistByID, id)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Bio,
		&i.ImageUrl,
	)
	return i, err
}
